module.exports = {
  "Ib7aYxQz8": true,
  "kB3j26e9MX": true,
  "KufQocmhZg": true,
  "sdjGDexqP1": true,
  "s-FH-81czL": true,
  "08SFZoRRE6bw": true,
  "5rrVoxJa0x": true,
  "jQl7ciusft": true,
  "klJ5WOMTykqK": true,
  "7xozRE3ZU_F": true,
  "RWA79WJt5i4E": true,
  "Vw9-OAWV-dR9": true,
  "549DwEKTpLdF": true,
  "u5UeE7bfRgkg": true,
  "w7PdZE5t0y_C": true,
  "Z-44ly1FHP4": true,
  "Ya8KsPPdIxZ": true,
  "YZSL_QxK5RO": true,
  "NMYk4YPKUYK": true,
  "uJO9a5ohP6VE": true,
  "CJBMJGD0-SaD": true,
  "UYtS00IgeZe": true,
  "4xdyk0hzaTI": true,
  "FK3Lcuob1m5": true,
  "jtkVz-jOHKoQ": true
}